@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Api rest - Calculate info level 3

participant Client_API
participant Fuego_de_quasar_MS
database BD_resistance

Client_API -> Fuego_de_quasar_MS: GET: https://challenge.engicoders.com/topsecret_split/{satellite_name}
Fuego_de_quasar_MS --> BD_resistance: saveInfo(satelliteEntity)

alt Cuando el satélite ya se encuentra guardado
Fuego_de_quasar_MS --> BD_resistance: updateByName(satellite)
end

BD_resistance --> Fuego_de_quasar_MS: la entidad guardada/actualizada
Fuego_de_quasar_MS --> Client_API: InfoResponse(position, message)

@enduml