version: '3'

services:
  spring:
    image: edhd8/fuego-de-quasar:1.3
    ports:
    - 8088:8088
    depends_on:
      - postgres
  postgres:
    ports:
      - 5433:5432
    image: postgres
    environment:
      POSTGRES_DB: 'resistance'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'