version: '3'

services:
  spring:
    image: edhd8/parrot-challenge:1.1
    ports:
    - 8088:8088
    depends_on:
      - postgres
  postgres:
    ports:
      - 5433:5432
    image: postgres
    environment:
      POSTGRES_DB: 'parrot_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'