INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Memoria USB', 51.25, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Laptop', 20000.00, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Mouse inalámbrico', 170.50, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Disco duro externo', 1560.00, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Pantalla', 15999.00, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Mousepad', 379.99, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Teclado inalámbrico', 740.00, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Pluma', 9.00, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Lápiz', 4.50, now());
INSERT INTO product_catalog (name, unit_price, created_at) VALUES ('Bocina', 100.00, now());